acme_ember_tests:
  pattern:     /tests.html
  defaults:
    _controller: FrameworkBundle:Template:template
    template:     'AcmeEmberBundle::tests.html.twig'

acme_ember_homepage:
    pattern:     /{url}
    defaults:
        url: null
        _controller: FrameworkBundle:Template:template
        template:     'AcmeEmberBundle::layout.html.twig'
    requirements:
        url: "^(?!api).+"
