# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    filters:
        cssrewrite: ~
        jsmin: ~
        emberprecompile: ~

sp_bower:
    install_on_warmup: true
    assetic:
        filters:
            js:
                - ?jsmin
    bundles:
        AcmeEmberBundle: ~
